### PR TITLE
ASM-5847: Improve parsing

### PR DESCRIPTION
**Pull request by ripienaar**
Incorporate a fix from Sushil.

We really should not be using scan to parse things ever :)

### CODE REVIEW

**Comment by ripienaar** [comment]
@sushilrai thanks for the headsup

**Comment by gavin-scott** [comment]
Looks good to me, will let @sushilrai merge since he's familiar with this issue.

**Comment by jkrauskopf** [comment]
@sushilrai Please review.

**Comment by ripienaar** [comment]
@gavin-scott @jkrauskopf I copy/pasted out of a gist from Sushil at https://gist.github.com/sushilrai/938dcf6c5e67f3a3014e so probably safe to take it as reviewed by Sushil

**Comment by gavin-scott** [comment]
Thanks guys.

**Pull request merged**
